responses:
  - "Woah there, {username}! Let's take a chill pill and give others a chance to talk."
  - "{username}, your enthusiasm is off the charts! How about we dial it back a little?"
  - "Everyone, witness {username}! The fastest typer in the West... Slow it down, partner."
  - "Hey {username}, this isn't a sprint. Let's pace ourselves, shall we?"
  - "It seems {username} has discovered the art of spam. Let's discover the art of silence."
  - "I'm sorry, {username}, I can't let you do that. Please slow down."
  - "I'm sorry, {username}, I'm afraid I can't do that. Please slow down."
  - "I'm sorry, {username}, I'm afraid I can't do that. Please slow down."
