name: Discord Notifications for Push and Releases

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Prepare timestamp
      if: github.event_name == 'push'
      id: date
      run: echo "::set-output name=timestamp::$(date -u +'%A, %B %d, %Y %H:%M:%S UTC' --date='${{ github.event.head_commit.timestamp }}')"

    - name: Send Discord Notification for Push
      if: github.event_name == 'push'
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
               "embeds": [{
                 "title": "🚀 New Commit Pushed!",
                 "description": "**Commit Details:**\n```Commit Message: ${{ github.event.head_commit.message }}```\n[View Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                 "color": 1127128,
                 "author": {
                   "name": "${{ github.actor }}",
                   "url": "https://github.com/${{ github.actor }}",
                   "icon_url": "https://github.com/${{ github.actor }}.png?size=32"
                 },
                 "thumbnail": {
                   "url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
                 },
                 "fields": [
                   {
                     "name": "Repository",
                     "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})",
                     "inline": true
                   },
                   {
                     "name": "Branch",
                     "value": "`${{ github.ref_name }}`",
                     "inline": true
                   },
                   {
                     "name": "Action Triggered By",
                     "value": "`${{ github.actor }}`",
                     "inline": true
                   }
                 ],
                 "footer": {
                   "text": "Timestamp: ${{ steps.date.outputs.timestamp }}"
                 }
               }]
             }' \
             $DISCORD_WEBHOOK_URL

    - name: Send Discord Notification for Release
      if: github.event_name == 'release'
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
               "embeds": [{
                 "title": "🎉 New Release Published!",
                 "description": "**Release Details:**\n```Release Name: ${{ github.event.release.name }}\nRelease Tag: ${{ github.event.release.tag_name }}```\n[View Release](https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.tag_name }})",
                 "color": 5814783,
                 "author": {
                   "name": "${{ github.actor }}",
                   "url": "https://github.com/${{ github.actor }}",
                   "icon_url": "https://github.com/${{ github.actor }}.png?size=32"
                 },
                 "thumbnail": {
                   "url": "https://github.githubassets.com/images/modules/logos_page/Octocat.png"
                 },
                 "fields": [
                   {
                     "name": "Repository",
                     "value": "[${{ github.repository }}](https://github.com/${{ github.repository }})",
                     "inline": true
                   }
                 ],
                 "footer": {
                   "text": "Released on: ${{ github.event.release.published_at }}"
                 }
               }]
             }' \
             $DISCORD_WEBHOOK_URL
