name: Discord Notification

on:
  push:
    branches:
      - main  # or any other branch you want to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send Discord Notification
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        curl -H "Content-Type: application/json" \
             -X POST \
             -d '{
               "embeds": [{
                 "title": "New Commit Pushed!",
                 "description": "A new commit has been pushed to the repository.",
                 "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}",
                 "color": 5814783,
                 "fields": [
                   {
                     "name": "Branch",
                     "value": "`${{ github.ref_name }}`",
                     "inline": true
                   },
                   {
                     "name": "Commit by",
                     "value": "`${{ github.actor }}`",
                     "inline": true
                   }
                 ],
                 "footer": {
                   "text": "GitHub Actions"
                 },
                 "timestamp": "${{ github.event.head_commit.timestamp }}"
               }]
             }' \
             $DISCORD_WEBHOOK_URL
